### ISSUE TITLE
Future support for NeoForge

### ISSUE THREAD

**Issue by 3gf8jv4dv** [DevBobcorn/AcryliCraft#1]
First of all, thank you for developing this mod! When I first saw this mod, I thought it was amazing!

Later I tried it out and the `1.20.1` + `forge` releases are available for Forge 1.20.1~1.20.4 and NeoForge 1.20.1, but NeoForge 1.20.2+ is not supported.

Just curious, will you develop a port for NeoForge in the future?

I apologize if my remarks were inappropriate in any way.

**Comment by DevBobcorn** [comment]
Sure, shouldn't be a problem since I'm using Architectury. I'll make a NeoForge port soon when I get the time.
