### ISSUE TITLE
1.6.0 NeoForge (both 20.6 & 21.0), transparent background does not work

### ISSUE THREAD

**Issue by 3gf8jv4dv** [DevBobcorn/AcryliCraft#10]
After entering the game, only the titlebar of the window is valid, and the game background is black.

Only _NeoForge_, _AcryliCraft_ and _YACL_ are installed.

<details>
<summary><s>Preview</s></summary>

</details>

_By the way, the same issue exists on NeoForge 20.6._

**Comment by DevBobcorn** [comment]
On Forge or NeoForge, it is necessary to set earlyWindowControl to false inside fml.toml to disable FML window intialization, otherwise the game window cannot be initialized properly.

**Comment by 3gf8jv4dv** [comment]
> On Forge or NeoForge, it is necessary to set earlyWindowControl to false inside fml.toml to disable FML window intialization, otherwise the game window cannot be initialized properly.

Oops, I forgot about that. _I was paying special attention to it when I used it before._

Sorry for the false positive, I will close this.
