### ISSUE TITLE
与sodium extra不兼容

### ISSUE THREAD

**Issue by liyuxiang-lyx** [DevBobcorn/AcryliCraft#11]
Win版本:22631.3737
版本:1.20.1
Fabric版本:0.15.11 
Fabric API版本:0.92.2
模组版本:AcryliCraft 1.4.0 Fabric
模组列表:
Sodium Extra
Sodium
AcryliCraft
Mod Menu
YetAnotherConfigLib
[Uploading crash-2024-06-20_23.39.40-client.txt…]()

**Comment by DevBobcorn** [comment]
Duplicate of #4.

**Comment by DevBobcorn** [comment]
这个问题是在1.5.1修的，不过暂时没有对应1.20.1，如果能用1.20.5或者1.20.6的话可以更新一下
