### ISSUE TITLE
与 Linux 不兼容

### ISSUE THREAD

**Issue by MetsukiMio** [DevBobcorn/AcryliCraft#12]
崩溃日志（kde在线剪贴板）：https://invent.kde.org/-/snippets/3172
虽然 dwmapi 不能直接移植，但至少在 Linux 上可以使 GLFW 窗口透明，linux 上主流的窗口管理器都可以强制执行模糊（

**Comment by DevBobcorn** [comment]
雀食不应该崩溃，我有时间看看

**Comment by MetsukiMio** [comment]
> 雀食不应该崩溃，我有时间看看

问题已经锁定为强行加载dll失败后崩溃（

**Comment by DevBobcorn** [comment]
等我有时间加上KDE支持再发新版本吧，光修一个崩溃好像也没啥用

**Comment by MetsukiMio** [comment]
> 等我有时间加上KDE支持再发新版本吧，光修一个崩溃好像也没啥用

kde支持不用做了，一般美化教程都已经开启了强制模糊，只要保证背景透明可用就行了，如果平台不对就直接禁用背景模糊自定义（
