### ISSUE TITLE
Embeddium donation prompt is rendered transparent

### ISSUE THREAD

**Issue by 3gf8jv4dv** [DevBobcorn/AcryliCraft#13]
Environment:
- Minecraft `1.21`
- NeoForge `21.0.141-beta`
- AcryliCraft `neoforge-1.6.1+1.21`
- Embeddium `1.0.7+mc1.21`
- YetAnotherConfigLib `3.5.0+1.21-neoforge`

<details>
<summary>Embeddium</summary>

![](https://github.com/user-attachments/assets/398def67-91f3-4ef6-993b-6f51884ac469)

</details>

<details>
<summary>With AcryliCraft</summary>

![](https://github.com/user-attachments/assets/4850333c-6b28-43af-a493-810e6d2779e2)

</details>

**Comment by DevBobcorn** [comment]
Seems like they have a time fingerprint to keep track of the installation time and show this prompt, making it tricky to reproduce this bug. Did you also find any other screen rendered like this?

**Comment by 3gf8jv4dv** [comment]
> Seems like they have a time fingerprint to keep track of the installation time and show this prompt, making it tricky to reproduce this bug.

I was also troubled by this problem at first: when I first discovered it, the game had many mods installed, and I was not sure whether it was caused by AcryliCraft. Later, I tried to modify the value after `"t":` in `embeddium-fingerprint.json` to ensure that it could be reproduced again.

> Did you also find any other screen rendered like this?

I have only found this one for now. If there are more similar situations in the future, I will give feedback in time.

**Comment by DevBobcorn** [comment]
> I tried to modify the value after `"t":` in `embeddium-fingerprint.json` to ensure that it could be reproduced again.

That did the trick, I'll see what I can do with the rendering.

**Comment by DevBobcorn** [comment]
![图片](https://github.com/user-attachments/assets/7e252c26-4068-4f10-ac03-050624b94745)
Oh, my fault. They accidentally render the background again after drawing the prompt content, and my code just clears up everything when background is rendered, including their already rendered UI. The 2 buttons weren't affected because they're rendered afterwards as renderables on the screen.

**Comment by DevBobcorn** [comment]
![图片](https://github.com/user-attachments/assets/d5a64611-8bda-469e-84dc-018fc90a7671)
![图片](https://github.com/user-attachments/assets/eb41fb24-86b2-44b3-ad4e-df6c2b1c0045)

This should fix this problem and similar problems alike.
