### ISSUE TITLE
Crash when clicking Config in the NeoForge mod list

### ISSUE THREAD

**Issue by 3gf8jv4dv** [DevBobcorn/AcryliCraft#18]
Log *(Deleted)*

**Comment by 3gf8jv4dv** [comment]
It looks like the crash is actually caused by YACL (many mods that depend on YACL have the same crash), but YACL has not been very active lately. I keep it open.

**Comment by DevBobcorn** [comment]
好像是NeoForge的锅，他们把设置界面的构造函数的参数改了

**Comment by DevBobcorn** [comment]
昨天点Embeddium的设置也会崩

**Comment by 3gf8jv4dv** [comment]
> 昨天点Embeddium的设置也会崩

Indeed, I just noticed it. *I initially thought you were talking about the video settings :/*

**Comment by DevBobcorn** [comment]
So I downgraded to NeoForge 20.0.78-beta, and everything just worked.

**Comment by DevBobcorn** [comment]
Guess NeoForge hasn't finished their breaking changes just yet, so breaking changes might still be made. I'll update my code when these changes are confirmed.

**Comment by 3gf8jv4dv** [comment]
> Guess NeoForge hasn't finished their breaking changes just yet, so breaking changes might still be made. I'll update my code when these changes are confirmed.

But they have marked 21.0.143 as stable.

**Comment by DevBobcorn** [comment]
I see, I'll update my dependency version and make changes correspondingly.
