### ISSUE TITLE
Auto toggle the dark mode switch based on Windows color mode

### ISSUE THREAD

**Issue by 3gf8jv4dv** [DevBobcorn/AcryliCraft#2]
After using it for a while, I suddenly discovered a shortcoming: dark mode can only be enabled/disabled manually.

I am using some programs that help me switch the Windows color mode and desktop wallpaper from light/dark during specific periods of time (to light during the day and to dark at night). Many software have added support for this feature, that is, switching related themes according to the color mode of the system.

If I manually enable dark mode in game and forget to switch it, the window will look darker during the Windows light mode with a brighter wallpaper. And vice versa.

I do not know if it is technically possible to implement this feature. I would really appreciate it if it could be implemented.

**Comment by DevBobcorn** [comment]
Nice suggestion! Implemented this just now, check it out!  ≧ᴥ≦

**Comment by 3gf8jv4dv** [comment]
The effect is what I expected and it is great. Thank you so much!
