### ISSUE TITLE
导致原版发光状态效果不渲染

### ISSUE THREAD

**Issue by chorusfruit-233** [DevBobcorn/AcryliCraft#20]
Win版本:22631.4037
版本:1.20.4
Fabric版本:0.16.2
Fabric API版本:0.97.1
模组版本:AcryliCraft 1.6.2
模组列表:
AcryliCraft
Mod Menu
YetAnotherConfigLib
Placeholder API
![2024-08-16_23 59 16](https://github.com/user-attachments/assets/6620e963-42a1-4551-964e-c82d88eee69f)

**Comment by DevBobcorn** [comment]
卧槽，可能是把实体Outline的Render Target的透明度通道也给画了，我去看看

**Comment by DevBobcorn** [comment]
草还真是，有时间了就更新修复
