### ISSUE TITLE
About proxy configuration in `gradle.properties`

### ISSUE THREAD

**Issue by 3gf8jv4dv** [DevBobcorn/AcryliCraft#26]
https://github.com/DevBobcorn/AcryliCraft/blob/dec430138b63389546df1d0ae4aad411df44f86f/gradle.properties#L5-L10

Sorry, but I tried to build manually with new code and got a `Connection refused` error. I checked the most recent commit and found this configuration.

Could we please add comments to this configuration or change `true` to `false`? After all, this is a public project and many users may not need this configuration. For Chinese Mainland users who are familiar with the development flow, they usually have their own proxy configuration.

**Comment by DevBobcorn** [comment]
Oh, I forgot that. Just a minute.
