### ISSUE TITLE
1.5.0 Fabric version number is written as `0.0.0`

### ISSUE THREAD

**Issue by 3gf8jv4dv** [DevBobcorn/AcryliCraft#3]
_First of all, kudos to you for the new features you implemented in 1.5.0! When I recently noticed that the relevant version of Minecraft 1.20.5 applied panoramas to multiple interfaces, I was thinking about whether to make relevant suggestions, but I didn't expect that you implemented it first. It feels very good!_

I noticed that the `version` field in the `fabric.mod.json` file was written as `0.0.0`; in contrast, the previous version was correctly written as `1.4.0`.

This is noticed because some launchers are able to read `fabric.mod.json` and display its version number. Plus after installing the _Mod Menu_ it prompted me that there was an update for the mod (but I did install _1.5.0_). Not sure if it was intentional or not, I thought about it and mentioned it anyway.

**Comment by DevBobcorn** [comment]
Well, actually it was a bug with the build script, the version number was not being properly written into `fabric.mod.json` so i hard coded it as a temporary fix. I'll look into the build script again and see if I can get it working.
