### ISSUE TITLE
1.5.0 Fabric and Sodium Extra will cause crashes

### ISSUE THREAD

**Issue by 3gf8jv4dv** [DevBobcorn/AcryliCraft#4]
Everything works fine when installing only _AcryliCraft_ and its dependencies, and then _Sodium_ or _Embeddium_. On this basis, launching the game after installing _Sodium Extra_ crashes without the game window even appearing.

Crash log: _(Deleted)_

**Comment by DevBobcorn** [comment]
Looks like it is that *AcryliCraft* and *Sodium Extra* both injected some code around the GLFW default window hints invocation, which confuses the mod loader and eventually leads to a crash. This can be a bit tricky, but I'll do some research and see if I can make them work together.

**Comment by DevBobcorn** [comment]
Guess I've found it:
https://github.com/FlashyReese/sodium-extra-fabric/blob/cdb15d75cdca99813b17b4e64c47000940009f8b/src/main/java/me/flashyreese/mods/sodiumextra/mixin/reduce_resolution_on_mac/MixinWindow.java#L31-L38

**Comment by DevBobcorn** [comment]
So, I replaced my `Redirect` with `Inject` and... It just worked! I thought `Inject` operations are not allowed in constructors. Anyway, the problem's solved:
![MAGIC](https://github.com/DevBobcorn/AcryliCraft/assets/49587038/86c9bd75-af19-49b0-89ce-6beb2430f21b)

**Comment by 3gf8jv4dv** [comment]
So glad to know this good news!

An off topic question by the way. Is _NeoForge_ not fully implemented because of some obstacles? Just curious, I am not in a hurry, after all _NeoForge_ is still in beta stage.

**Comment by DevBobcorn** [comment]
Yep.  YACL is not yet available for NeoForge 1.20.5, and NeoForge 1.20.5 seems to have introduced some breaking changes. So it will probably still be a while before everything gets updated.
