### ISSUE TITLE
1.20.6 NeoForge port

### ISSUE THREAD

**Issue by 3gf8jv4dv** [DevBobcorn/AcryliCraft#5]
NeoForge maintainers have just marked NeoForge 20.6 as stable. Currently, YACL has also been released for NeoForge 20.6. Curious if you have any further plans for this.

Regards.

**Comment by DevBobcorn** [comment]
I'll check Architectury's updates and see if they can get the build script working for NeoForge. You can expect NeoForge support re-added soon if everything goes fine.
